project_name: mytoken
before:
  hooks:
    - go mod tidy
dist: results
builds:
  - id: client
    main: ./cmd/mytoken/main.go
    binary: mytoken
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{ if eq .Os "darwin" }}macOS{{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}32-bit{{- else if eq .Arch "amd64" }}64-bit{{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: client-pkg
    package_name: mytoken
    file_name_template: >-
      {{ .PackageName }}_{{ .Version }}_
      {{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}
    builds:
      - client
    homepage: https://mytoken-docs.data.kit.edu/
    maintainer: Gabriel Zachmann <gabriel.zachmann@kit.edu>
    description: Mytoken is a command line client for the central web service mytoken. It can be used to easily obtain OpenID Connect access tokens across devices.
    license: MIT
    formats:
      - deb
      - rpm
    release: "1"
    section: misc
    bindir: /usr/bin
    contents:
      - src: config/example-config.yaml
        dst: /usr/share/doc/mytoken/example-config.yaml
        type: config
    overrides:
      rpm:
        file_name_template: >-
          {{ .PackageName }}-{{ .Version }}.
          {{- if eq .Arch "386" }}i386{{- else if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - client
    image_templates:
      - "oidcmytoken/mytoken:latest"
      - "oidcmytoken/mytoken:{{ .Tag }}"
      - "oidcmytoken/mytoken:{{ .Major }}"
      - "oidcmytoken/mytoken:{{ .Major }}.{{ .Minor }}"
    dockerfile: cmd/mytoken/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=mytoken"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  prerelease: auto
  draft: true
  github:
    owner: oidc-mytoken
    name: client
  name_template: "{{.ProjectName}} {{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
