project_name: mytoken
before:
  hooks:
    - go mod tidy
builds:
  - id: client
    main: ./cmd/mytoken/main.go
    binary: mytoken
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
nfpms:
  - id: client-pkg
    package_name: mytoken
    builds:
      - client
    homepage: https://mytoken-doc.data.kit.edu/
    maintainer: Gabriel Zachmann <gabriel.zachmann@kit.edu>
    description: Mytoken is a command line client for the central web service mytoken. It can be used to easily obtain OpenID Connect access tokens across devices.
    license: MIT
    formats:
#      - apk
      - deb
      - rpm
    release: 1
    section: misc
    contents:
      - src: config/example-config.yaml
        dst: /etc/mytoken/example-config.yaml
        type: config
checksum:
  name_template: 'checksums.txt'
release:
  draft: true
  name_template: "{{.ProjectName}} {{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
