# The issuer url of the mytoken instance you want to connect to
instance: "https://mytoken.data.kit.edu"

# Mytokens can be named, so they can be identified better; if specified this string is used as a prefix.
# The special value <hostname> is substituted with your machine's hostname
token_name_prefix: "<hostname>"

# The default capabilities for mytokens
default_token_capabilities:
    - "AT"
    - "tokeninfo"             # allows to query the tokeninfo endpoint for different information about the token

# The default provider to use
default_provider:

# Here you can assign names to providers
providers:
  egi: "https://aai.egi.eu/auth/realms/egi"
  egi-dev: "https://aai-dev.egi.eu/auth/realms/egi"
  wlcg: "https://wlcg.cloud.cnaf.infn.it/"

