# The issuer url of the mytoken instance you want to connect to
instance: "https://mytoken.data.kit.edu"

# Mytokens can be named, so they can be identified better; if specified this string is used as a prefix.
# The special value <hostname> is substituted with your machine's hostname
token_name_prefix: "<hostname>"

# The default capabilities for mytokens
default_token_capabilities:
    - "AT"
    - "tokeninfo"             # allows to query the tokeninfo endpoint for different information about the token

# The default provider to use
default_provider:

# Determines if WLCG Bearer Token Discovery
# (https://github.com/WLCG-AuthZ-WG/bearer-token-discovery/blob/master/specification.md) should be used or not
# (mytokens passed more directly, i.e. through command line options take precedence)
use_wlcg_token_discovery: true

# Here you can assign names to providers
providers:
  egi: "https://aai.egi.eu/auth/realms/egi"
  egi-dev: "https://aai-dev.egi.eu/auth/realms/egi"
  wlcg: "https://wlcg.cloud.cnaf.infn.it/"

